name = "HGF"
uuid = "63d42c3e-681c-42be-892f-a47f35336a79"
authors = ["Peter Thestrup Waade ptw@cas.au.dk", "Jacopo Comoglio jacopo.comoglio@gmail.com", "Christoph Mathys chmathys@cas.au.dk\n                and contributors"]
version = "0.1.0"

[deps]
ActionModels = "320cf53b-cc3b-4b34-9a10-0ecb113566a3"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
Distributions = "0.25"
RecipesBase = "1"
Turing = "0.21"
julia = "1.7"
