# GitHub action to automerge compathelper PRs. Only merges if tests pass due to branch protections in the repo.

name: automerge-CompatHelper-prs

on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'CompatHelper Julia'}}    
    
    steps:
    # Checkout action is required for token to persist
    - name: Enable auto-merge for CompatHelper PRs
      run: gh pr merge --auto --merge "$PR_URL" # Use Github CLI to merge automatically the PR
      env:
        PR_URL: ${{github.event.pull_request.html_url}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Auto approve CompatHelper PRs
      if: github.actor == 'CompatHelper Julia'
      uses: hmarr/auto-approve-action@v3
      with: 
        github-token: ${{ secrets.GITHUB_TOKEN }}